- lib/GADS/Record.pm
I have no idea who/why made this fatal in recent perl versions, but there it is :/
> Fix for recent perls - my( ..., my  ) is fatal

- lib/GADS/Role/Presentation/Record.pm
- public/css/ctrlo-bootstrap.css
- public/js/linkspace.js
- sass/ctrlo-bootstrap.scss
- views/data_table.tt
- views/snippets/datum.tt
This deals with the fact that any table can have `n` columns that we have no control over. Any column can contain text depending on its type, and this text can be very large. It may also contain links.
I ended up going for a disclosure widget, in which the column header name is added to provide proper context. The column content is disclosed in familiar style, with a minimum width. If the width exceeds the viewport, it gets adjusted in its position.
This is still a hack to patch a deeper problem; having columns with lots of PRs, or columns with large amounts of text are a UX anti pattern. Ideally GADS administrators should be aware of how to effectively compose tables.
Any of the other potential solutions ("detail views", "card view", "list of cards", "rotate the table") come with other …
> Disclosure widget for large text columns

- views/layouts/main.tt
It seems that the `data-page` attribute got removed from the `<body>` element during a merge. This caused the JS to throw. 
Likely this also sorts Brass Issue 428 - Unable to add new permissions.
> Brass issue #427 - Add current page as attribute to body element

- public/css/ctrlo-bootstrap.css
- sass/ctrlo-bootstrap.scss
- views/data.tt
- views/data_table.tt
This PR:
* makes _Rows per page_ part of the grid
* styles the _previous page_ and _next page_ links
* removes _disabled_ links; this is an antipattern
* adds assistive visually hidden labels to _previous page_ and _next page_
* improves semantics for viewtype buttons
> Style 'rows per page' select and 'previous/next' page

- views/layout.tt
This should sort Brass issue #463 - duplicate save buttons in layout.
> Only show field save button when relevant

- public/css/ctrlo-bootstrap.css
- sass/_permissions.scss
This brings back the tabpanel layout as removed by a recent merger. It's also been moved to its proper sass import file.
> Reintroduce layout tabpanel CSS

- public/css/ctrlo-bootstrap.css
- sass/ctrlo-bootstrap.scss
The solution as included in the PR is quiet simple. It allow html elements to go outside the boundaries of a panel. But since a style to actually hide overflowing elements was in place, this change might break other things. It might have been there for a reason I don't know of. Maybe you have any idea? If not, just keep in mind that if you see something outside a panel that should've been cut off/hidden, this might be the reason :)
> Allow select widgets to break out of its panel

- public/js/linkspace.js
It seems the focus was still on the radio button after closing,
causing a click event to be triggered when trying to open up
another widget.
> Fix weird reopening of single select widget in firefox

- lib/GADS/Instances.pm
- lib/GADS/Layout.pm
- lib/GADS/Records.pm
Using find() instead of search()->next() in this well-tested code seems
like a worthwhile low risk improvement.
> Further DBIC simplification

- bin/migrate-db.pl
Just discovered the correct way to get to the configuration: use Dancer2's config()
> simplify reading config in migrate-db using Dancer2

- webdriver/t/create_view.t
- webdriver/t/lib/Test/GADSDriver.pm
Before creating a view, test all records are shown.  This means we need
to look for a different attribute (views use "aria-label", all records
use "data-thlabel") and filter out the default fields.
I could have filtered out those fields using Test::Deep, but in keeping
with the Test2 approach used in Test::GADSDriver, I decided not to.
However, I couldn't figure out how to check a subset of fields easily
using Test2 so I've commented on that as something to do in future.
> WebDriver tests for all records shown

- lib/GADS/Column.pm
The only encode_base64() call in this module was removed in 9f92b02a69a.
> Remove an unused dependency

- Makefile.PL
Commit 6f8dd03bb02ef replaced PhantomJS with Chrome, causing test to
fail in a development environment with the old modules installed.
The failing tests, t/001_base.t and t/002_index_route.t, only run in the
presence of a config.yml file, so our current CI setup did not notice
this problem.
> Update the CPAN dependencies

- config.yml-example
- environments/development.yml
- environments/production.yml
- public/dispatch.fcgi
Redirect warnings to Log::Report.
In production, only use Log::Report::Dispatcher::Syslog, by making it the default logger.  In development, only use Log::Report::Dispatcher::File to log at debug level to STDOUT with a timestamp using the "LONG" format.
Developers can override or extend these settings by creating their own `environments/development_local.yml`.
> Minor logging improvements

- lib/GADS.pm
- webdriver/t/lib/Test/GADSDriver.pm
This should finally stop the webdriver tests failing in CI.
> Give each page a unique indentifier name

- bin/date-format.pl
- bin/import.pl
Nothing in these scripts calls a method on Path::Tiny or its `path()` constructor.
> Stop loading an unused module

- .github/workflows/tests.yml
- bin/setup_database
Separate out the "setup the database" and "run the application" parts.
While I'm here, fix setting the linkspace user's password.
> Make a setup script more reusable

- lib/GADS.pm
- lib/GADS/API.pm
Calling header() instead of response_header() emits the warning:
DEPRECATED: header keyword. Please use the 'response_header' keyword instead of 'header'
> Avoid Dancer2 warnings

- .github/workflows/tests.yml
Ubuntu 22.04 does not support Firefox or Geckodriver easily, so stick with 20.04 for that.
> GitHub Actions: update software versions

- Makefile.PL
GADS::SAML, which depends on various Net::SAML2 modules and URL::Encode, has existed since 51e3f70.
> Add missing dependencies

- .github/workflows/tests.yml
This test script fails with the new Linkspace 2 changes in the uiux branch.  I've done a little work on fixing the tests, but they don't pass yet.  Disabling them will make it easier to spot new problems as we will no longer expect the tests to fail.
> Stop running webdriver/t/create_view.t in CI

- lib/GADS.pm
- views/wizard/record_alert_me.tt
- Removed 'Never option from the alert frequency options.
- Modified some of the displayed text for the alert modal header and buttons. 
- Added A button called 'Remove' to the alert modal that will replace the 'Never' option in the Alert drop-down.
- The 'Remove' button functions in exactly the same way as the create button but instead it's fixed to always write the 'Never' value in the alert frequency. (as well as having its own return message).
> Added Remove Alert button

- views/wizard/record_alert_me.tt
Added an if statement so the 'remove' button only displays when modifying an existing alert, as opposed to creating a new one.
> Fixed display conditions on 'Remove' btn

- src/frontend/components/form-group/calc-fields/lib/component.js
- src/frontend/components/form-group/textarea/lib/component.js
- views/edit.tt
- Changed the field type of calc from input to textarea.
- Changed the re-calc triggers to point at text-area instead of input.
- Added class + functionality to calc textareas,  to allow text-areas to resize based on the content returned by the Calc. (on load and on change).
> Changed calc type from input to auto adjust textarea

- src/frontend/components/data-table/lib/component.js
Data tables were not adding click event on page or page-length change, this has now been fixed
> Fix for data tables

- lib/GADS/Schema/Result/Site.pm
There were 2 different fields within account request notes for "Notes" - it looks like one of them was added in error (as the "user" class has no "notes" field). As such, I have removed the "extra" one and fixed the naming and settings of the field that was producing an error.
> Account request notes fix

- lib/GADS/Schema/Result/Site.pm
- views/fields/select_single.tt
- views/user/my_account.tt
- Can now disable dropdowns
- Now have notes field in myaccount
> Minor bug fixes

- src/frontend/components/data-table/lib/component.js
- src/frontend/js/lib/util/mapper/mapper.test.ts
- src/frontend/js/lib/util/mapper/mapper.ts
- src/frontend/js/lib/util/typeahead/lib/Typeahead.ts
Due to the typeahead library not handling AJAX "correctly" according to current ES standards. AJAX request has now been redone as synchronous in order to mitigate this. ID field in mapping redone as this was also causing issues (and tests updated accordingly)
> Fixed typeaheads not working for large number of

- lib/GADS/Schema/Result/User.pm
It was found that the value $params{account_request} was defined regardless of if it was a 1 or a 0, therefore a check is now present for if it is (currently) a 1 and this request is setting it to 0 (thus approving an account).
> Double email sending fix

- src/frontend/components/form-group/input/lib/component.js
- src/frontend/js/lib/util/filedrag/lib/filedrag.ts
- Added options to stop Blueimp high-jacking document drop event
- Fixed incorrect direction for greater than arrow on `response >= 400`
- Fixed drop with multiple targets on screen not resetting correctly
> Fix for file drag errors

- src/frontend/components/form-group/display-conditions/lib/component.js
- src/frontend/components/form-group/filter/lib/component.js
Found that bootstrap-select was being applied to the wrong stage of the render pipeline for the querybuilder, meaning it had no value on reload. This has now been fixed.
> Fix for selects not populating on load

- src/frontend/components/form-group/display-conditions/lib/component.js
- src/frontend/components/form-group/filter/lib/component.js
Querybuilder is not showing correct values for the filter action (i.e. not equal, is empty, etc.) - for now as an immediate fix to users, the typeahead and bootstrap-select code has been removed to be changed and fixed for next release.
> Fix for query-builder not showing correct values

- src/frontend/components/form-group/filter/lib/component.js
- src/frontend/js/lib/util/typeahead/lib/Typeahead.ts
- src/frontend/js/lib/util/typeahead/lib/TypeaheadBuilder.ts
Typeahead was not filtering values correctly due to error in TypeScript, this has now been fixed
> Fixed bug in typeahead code

- .babelrc
Optimisation through Babel was causing globes to not work, Plotly has been removed from the optimisation process - tested and working locally
> Fix for incorrect optimisation of Plotly JS

- src/frontend/components/form-group/filter/_filter.scss
- src/frontend/components/form-group/filter/lib/component.js
- src/frontend/components/typeahead/_typeahead.scss
- src/frontend/css/stylesheets/general.scss
- src/frontend/js/lib/util/typeahead/lib/Typeahead.ts
- Added bloodhound for debounce and query efficiency
- Upped limit on results (bug on typeahead means that setting this to the max you expect means that the system will be erratic with the returned results, and miss values off)
- Added scroll and max height to result display
> Typeahead column header fix

- src/frontend/components/data-table/lib/component.js
Span in fullscreen button was having classes erroneously applied, this has now been fixed.
> Fixed bug on fullscreen button

- .github/workflows/tests.yml
V16 is deprecated by GitHub, tests now require v18 as minimum - tests modified as necessary.
> Version bump for NodeJS tests

- Makefile.PL
Commit 449838bf88 changed the minimum version of PDF::Table required by GADS::Schema::Result::Report, but did not state this in the Makefile.PL. That commit does not say why we require this newer version.
GADS::Record still requires a minimum version of "0.11.0" which probably also needs updating for consistency, but without understanding why GADS::Schema::Result::Report needs a newer version, I don't know.
> Fix the minimum version required of PDF::Table

- package.json
Slightly concerned that the compatibility isn't necessarily in place for the `import().then()` used in the code for chunking (this is _not_ IE11 compatible) - original config allowed this to (possibly) pass through as any browser with less than 0.2% share should be ignored (IE has less than this according to [caniuse.com](http://caniuse.com))
> Added `browserslist` to package.json

- src/frontend/css/stylesheets/base/_global.scss
- views/snippets/button_list.tt
- views/snippets/header_table_form.tt
- Created CSS for separator
- Moved `record_edit_extra.tt` out of `header_table_form.tt` and into `button_list.tt` in order to allow download options in extensions to display in correct (new) place
**This edit will break GADS-extensions - please install newer version in order to ensure correct display**
> Changes to Download Options

- .github/workflows/tests.yml
- webdriver/t/create_view.t
- webdriver/t/lib/Test/GADSDriver.pm
Following substantial UI changes, the WebDriver tests have been broken.  These changes update the tests to work better with the new UI.  Those that I haven't fixed yet are skipped.  We run all passing tests in CI Using GitHub Actions.
Remaining work involves fixing tests in create_view.t inside the SKIP block, removing this block, and uncommenting the `assert_error_absent()` calls after fixing their behaviour when using Chromium.
> Fix the create_view.t tests and run them in CI

- rex/Rexfile
Original clone was for fork, not original
> Moved rexfile for clone

- bin/app.pl
Insignificant change, but I've used it a couple of times when I've had multiple instances running locally
> Allow setting of port on launch through environment variable

- .github/workflows/tests.yml
Due to constantly receiving email stating the tests have failed, I have removed the failing tests for now (as they are failing due to an issue with GH actions, not an issue with the tests).
> Removed erroring Firefox tests

- src/frontend/components/data-table/lib/component.js
Invalid scoping and incorrect parameters caused `undefined` error
> Fix for datatable console error

- lib/GADS.pm
- src/frontend/components/button/_button.scss
- views/admin/audit.tt
As session filter doesn't clear, a clear filter button had to be added. The icon is the best I feel I could do as there isn't one I feel is suitable within our icon set.
> Added clear filter button

- src/frontend/components/form-group/filter/lib/component.js
A bug with unknown cause is meaning that dynamic loading of Typeahead as a chunk is causing filter typeahead on curvals to be rendered without rules across the board. For now, dynamic loading in this instance has been removed as a short-term solution, a longer-term solution will be pursued going forward.
> Fix for filter typeahead querybuilder bug

- src/frontend/js/lib/util/typeahead/lib/Typeahead.ts
Made TypeAhead use 1+ characters before suggestions. This is to mitigate issue with view filters.
> Typeahead Fix

- lib/GADS.pm
This will fix webdriver and cypress failures.
> Bareword causing error on run

- src/frontend/components/form-group/tree/lib/component.js
- src/frontend/js/lib/validation.js
It had to be done this way, if you remove _either_ deselects, it stops working. Why this is, I don't know, but I'm blaming JSTree!
> Fix for selecting and deselecting tree nodes

- src/frontend/css/stylesheets/general.scss
It was found that when the variables were _not_ loaded first in the imports (`general.scss`) the font being used was incorrect.
> Fix for CSS not providing correct font

- webdriver/t/lib/Test/GADSDriver.pm
At some point between 3519813b and 217c0daa these tests began failing. From a quick glance, I don't understand why.  The tests failed as follows:
```
not ok 23 - The manage tables page is visible
```
The "Manage Tables" page contains no element matching the "th.sorting" selector so it makes sense that this test fails.  Instead of checking for that, check that the active navigation link contains the word "Tables".
> Fix WebDriver tests

- .gitignore
This file is added as part of the chrome testing (it's part of Chrome's anti-phishing/security checks, according to google) - it's not required to it has been added to .gitignore as to ensure it isn't added by mistake
> Added Cypress downloads.html to ignore

- src/frontend/js/lib/util/mapper/formdataMapper.test.ts
- src/frontend/js/lib/util/mapper/formdataMapper.ts
We will now rely on `FormData` methods to catch erroneous objects being passed in. It may be worth working towards a more robust mapper for future use, but for now, this version is more than suitable for our needs.
> Fixed form mapper error where File objects were not being mapped correctly

- src/frontend/components/data-table/lib/component.js
- src/frontend/js/lib/util/mapper/formdataMapper.test.ts
Datatable was not being properly reinitialized within the code, an override parameter has been added to mitigate this.
> Updated fullscreen to allow for filtering and searching

- views/snippets/user_column_permissions.tt
Typo in `wizz?ard` was causing permissions to not be saved
> Fix for user permissions not saving

- src/frontend/components/data-table/_data-table.scss
Due to upgrade on DT to 2.0, the class names for this component had changed; this particular element had been missed in the SCSS changes and should now be corrected with this PR.
> Fix for datatables loading graphic displaying in the incorrect place [B: 1738]

- lib/GADS.pm
- lib/GADS/Schema/Result/User.pm
- src/frontend/components/data-table/lib/component.js
- src/frontend/components/modal/lib/component.js
- src/frontend/components/modal/modals/user/lib/component.js
- views/wizard/user_add.tt
Initial commit contained "odd" changes due to merge of current dev branch - this is taken from the current dev branch (post v2.5.11).
> Reject reason complete [B: 1647]

- lib/GADS/Column/Tree.pm
Sub `values_for_timeline` was missing from `lib/GADS/tree.pm` and caused a panic when the show all values in the timeline config was selected.
> Added missing  sub

- src/frontend/components/timeline/lib/component.js
Rendering of timeline is now async in order to ensure requests don't lock up the system and navigation can still be performed away from the timeline
> Made timeline async

- src/frontend/components/form-group/calc-fields/lib/component.js
Calc field changes were triggering on all fields, causing the system to slow down significantly - the updated code only changes fields when this is necessary now.
> HOTFIX: Updated fields to only change when necessary (B:1766)

- views/navigation/dropdown_actions.tt
On testing, it was found that download option was missing from the actions menu. This was due to the count parameter no longer being passed in due to a previous fix implementation.
> Removed count parameter from download options [B:1798]

- src/frontend/components/form-group/value-lookup/lib/component.js
Should this error, the system will currently halt the script should it error - this is not correct functionality and a try/catch block is used here.
This was introduced due to the changes required for use with the autorecover functionality.
> Fix for value-lookup component not being able to continue when erroring [B:1807]

- src/frontend/components/form-group/filter/lib/component.js
Filter typeaheads were returning an error when trying to save views using them on curvals - this error was caused by #521
In testing, the above caused issues when using short names for filtering on curvals. This issue has been resolved another way.
> Rolled back error causing filter typeaheads not to work as expected [B: 1815]
