- lib/GADS/DB.pm
Clean up the mess I made in https://github.com/ctrlo/GADS/pull/1/files
This is the core problem with the codebase. Given I produced the original screwup it is only fitting I fix it for good. The diag has now been extended to make this easier to spot/rectify in the future. See the commit msg for the full text.
Cheers!
P.S. This is unrelated to https://github.com/ctrlo/GADS/issues/8, which is still somewhat unresolved.
> Fix incomplete rsrc reregister

- .gitignore
- .jshintrc
- package.json
- public/css/ctrlo-bootstrap.css
- sass/_branding-colours.scss
- sass/ctrlo-bootstrap.scss
- add node and npm support
- add sass
- move branding colours to separate sass import
- replace references to primary colour with sass variable
- write early .jshintrc, add jshint support
> Sass support

- public/css/ctrlo-bootstrap.css
- public/js/linkspace.js
- sass/ctrlo-bootstrap.scss
- views/layout.tt
- views/snippets/layout_permissions.tt
This is a working tab panel layout for field editing. The controls footer has not been touched as I'd like to have that consistent with the _Edit Record_ functionality.
Mainly I'd like to hear thoughts on this. Personally I think it works very well, it's accessible, and can be operated by mouse as well as keyboard (arrow-left, arrow-right to cycle tabs).
> Issue 466  layout settings tabpanel

- README.md
- public/css/ctrlo-bootstrap.css
- sass/_navigation.scss
- sass/ctrlo-bootstrap.scss
- views/data_table.tt
- views/snippets/navigation.tt
This PR:
* improves quicksearch styling and adds it to the page header
* adds responsive styling to the page header
* clarifies front-end workflow in the README
> Issue #468, #467: header content positioning

- public/css/ctrlo-bootstrap.css
- public/js/linkspace.js
- sass/_data-table.scss
- sass/ctrlo-bootstrap.scss
- views/data_table.tt
- views/edit.tt
Hi Andy,
This handles dependencies on fields, with all the logic separated out into `linkspace.js`.
One case I'm not sure I'm handling correctly is the `tree` column type, can you explain what the special case is around this column type so I can account for it?
This PR also sorts the floating data table header issue.
> Dropdown widget dependent field

- views/edit.tt
This might conflict w/ feature-ctrlo-513. Let me know if they do once you merge one or the other.
> Improve styling of listed sub-records

- public/js/linkspace.js
- views/edit.tt
The value of the clicked button will now also be posted.
> Disable submit button on save

- webdriver/t/lib/Test/GADSDriver.pm
- webdriver/t/login.t
Further iteration on an initial idea..
> Webdriver tests

- views/snippets/navigation.tt
- webdriver/t/create_view.t
- webdriver/t/lib/Test/GADSDriver.pm
- webdriver/t/login.t
In order to get closer to testing views and filters, I have implemented table management tests.
> Webdriver table management

- webdriver/README.md
- webdriver/t/create_view.t
- webdriver/t/lib/Test/GADSDriver.pm
- webdriver/t/login.t
I experimented with making the application slower and watched how the tests failed.  I expect the tests will perform better in various development environments after these changes.  If you find these changes helpful, I can start using this approach more widely and make it more configurable.
> Webdriver robustness

- lib/GADS/Graph.pm
- lib/GADS/MetricGroup.pm
- lib/GADS/Record.pm
- lib/GADS/View.pm
When we only want one row, find() makes more sense than search().
> Call more suitable DBIC methods

- webdriver/t/create_view.t
- webdriver/t/lib/GADSDriver.pm
- webdriver/t/lib/Test/GADSDriver.pm
This tightens up the tests a little and also adds and removes fields from a table.
> More WebDriver tests

- public/css/ctrlo-bootstrap.css
- sass/ctrlo-bootstrap.scss
- views/layout.tt
Fixes https://github.com/ctrlo/GADS/issues/108
> 673 Button styling

- webdriver/t/lib/Test/GADSDriver.pm
This makes the WebDriver tests pass against master again.
> Webdriver improvements

- webdriver/t/lib/Test/GADSDriver.pm
5ffe635 added a new submit button, which meant the old test code didn't
know which one to click.  This change makes the button selector more
specific.
> Fix the WebDriver tests

- webdriver/t/lib/Test/GADSDriver.pm
These changes should fix the common test failures in GitHub actions.
> Webdriver timing fix

- .github/workflows/tests.yml
- bin/setup_for_webdriver
- webdriver/t/lib/GADSDriver.pm
- webdriver/t/lib/Test/GADSDriver.pm
When using GitHub Actions as a continuous integration platform, run the WebDriver tests in Chromium as well as Firefox.  This gives a better idea of how the application works across different browsers.
> Run the Webdriver in Chromium for CI

- .github/workflows/tests.yml
- Dockerfile
- Vagrantfile
- bin/output_cpanfile
This reduces similar copy/pasted code and makes it into a new command.
I don't currently use Docker or Vagrant, although I have done in the past so I'm familiar with their syntax.  If I've made any mistakes in the Dockerfile or Vagrantfile, please let me know so we can fix them.
> Reuse cpanfile generation code

- .gitignore
- package.json
- yarn.lock
Updated gitignore to include unnecessary Makefile and others in webdriver directory and updated package.json to fix outdated and deprecated yarn/npm packages.
> Package changes

- src/frontend/components/record-popup/lib/component.js
Sorry last PR had a bracket in the wrong place. 
This is the correction.
> Corrected small syntax error

- views/snippets/datum.tt
An error in the file meant that the status wasn't displaying correctly when viewing the field data - this is now fixed
> Error in datum RAG status fix

- views/user/user_edit.tt
- views/wizard/user_add.tt
> Changed dropdown for users to searchable units

- views/user/user_edit.tt
- views/wizard/user_add.tt
User edit and create doesn't appear to be working with searchable fields on EPF-Copy - rolled back previous changes and committed as release due today on Escapade
> Fix for user editing not working correctly

- src/frontend/components/form-group/filter/lib/component.js
- src/frontend/js/lib/util/typeahead/lib/Typeahead.ts
- src/frontend/js/lib/util/typeahead/lib/TypeaheadBuilder.ts
- src/frontend/js/lib/util/typeahead/lib/TypeaheadSourceOptions.ts
Typeahead query was not being sent correctly and was returning all results, rather than the filtered list, this has now been fixed
> Updated typeahead with fix - JS build required

- package.json
- webpack.config.js
- yarn.lock
- Added code to webpack config to allow source mapping and dev mode to apply appropriate settings
- Added build:dev task to package.json (this applies the correct variables in order for the config to generate maps etc for debugging)
- Removed unnecessary items from package.json
- Added test:watch task to package json - this will check for any code changed since last commit and perform tests against any new or changed JS files as required
> Webpack and package changes

- src/frontend/components/button/lib/create-report-button.test.js
Error in test fixed to now pass (missing global jQuery instance for tests).
> Fix for failing test

- views/edit.tt
The alternative is to create a "multivalue textbox" than has the label, then either a textbox with each value (one per line), or multiple textboxes
> Moved label outside of header

- views/edit.tt
- views/fields/textarea.tt
Have modified both templates in order to bring formatting in line with current standard
> Formatting was incorrect on multival calc fields

- views/wizard/user_add.tt
Notes field on User Wizard had "vanished" for some reason. This has been added back in!
> Fix for fields not displaying

- package.json
- src/frontend/components/form-group/display-conditions/lib/component.js
- src/frontend/components/form-group/filter/lib/component.js
- src/frontend/css/stylesheets/external.scss
Probably need to regenerate the lockfile, but mine is a mess, so I'll leave that to you! :smile:
> Bootstrap-select added

- src/frontend/components/filedrag/_filedrag.scss
- src/frontend/components/form-group/input/lib/component.js
- src/frontend/js/lib/util/common.test.js
- src/frontend/js/lib/util/common.ts
- src/frontend/js/lib/util/filedrag/lib/filedrag.ts
- CSS modified for error display
- Error display for drag added
- Fixed bug in saving form
- Fixed bug with multiple separate inputs on one screen not showing correct behaviour
- Added fromJSON utility function to handle whether response could be either string or JSON object
- Added unit tests for the above
> Fixed bugs in file drag and drop

- lib/GADS.pm
- lib/GADS/Role/Presentation/Column.pm
- src/frontend/components/data-table/lib/component.js
- src/frontend/components/form-group/_form-group.scss
- views/data_table.tt
- views/tables/basic_table.tt
- Added code to display RAG according to the inputted value on enabled_rags of the layout
- Removed typeahead from date fields as this would over-complicate functionality
> Typeahead rag fix

- src/frontend/components/data-table/lib/component.js
- views/admin/audit.tt
Accidentally deleted the branch
> Auditfullscreen

- views/user/user_request.tt
Fixed bug where notes weren't showing due to incorrect field naming.
> Fix for notes not showing

- lib/GADS/API.pm
- src/frontend/components/dashboard/lib/react/api.tsx
- src/frontend/components/dashboard/lib/react/app.tsx
Changed put requests to use request body (as should be the case) mitigating 414 errors.
> Fix for put requests

- babel.config.js
> Added new babel config file and added comment as clarification for exclude

- src/frontend/components/sidebar/_sidebar.scss
- src/frontend/components/sidebar/lib/component.js
- src/frontend/css/stylesheets/base/_global.scss
- views/navigation/main_menu.tt
- Hide sidebar until load is complete, then show in the correct state
- Added transitions to ensure that pop out and in is "cleaner"
> (Possibly) fixed sidebar "jarring" load

- bin/docker.sh
- bin/frontend.sh
- bin/wait-for-it.sh
- compose-dev.yml
- docker-compose.yml
Modifications added as provided by Digitpaint - these can aid development (dependent on requirements) and as such have been added to single feature commit
> Modifications to docker config

- src/frontend/components/form-group/input/lib/component.js
Had to use a "refresh" event, mainly in order to not have
> Fix for logo not changing on upload of new logo.

- lib/GADS/Column.pm
- lib/GADS/Schema/Result/Report.pm
- Removed header repeat[^1]
- Changed column width to fixed width for left hand side
[^1]: This is dependent on a `PDF::Table` code edit that is required due to a bug in their code
> Reporting edits

- bin/migrate-db.pl
This script is still annoyingly chatty, but less so before.
> Silence "Prototype mismatch" warnings

- lib/GADS.pm
- src/frontend/components/button/_button.scss
- src/frontend/components/button/lib/component.js
- src/frontend/components/data-table/_data-table-row.scss
- src/frontend/components/data-table/_data-table.scss
- src/frontend/components/data-table/lib/component.js
- src/frontend/components/data-table/lib/helper.js
- src/frontend/components/form-group/_fieldset.scss
- src/frontend/css/stylesheets/definitions/_variables.scss
- views/fields/sub/add_remove.tt
- views/tables/basic_table.tt
- views/view.tt
This update changes the look and feel of the view settings page according to the redesign and improves the user experience for the fields selection.
> Table view fields

- src/frontend/components/data-table/lib/component.js
- src/frontend/components/form-group/filter/lib/component.js
- src/frontend/components/form-group/input/lib/component.js
- src/frontend/components/form-group/select-widget/lib/component.js
- src/frontend/components/modal/lib/component.js
- src/frontend/components/modal/modals/curval/lib/component.js
- src/frontend/components/more-less/lib/component.js
- src/frontend/components/summernote/lib/component.js
I have found that the datatables code threw a fit on use with the current changes, I've done some digging and found that the reference to this as self within the code is the issue due to me being incorrect about scoping in some places. I have fixed any scoping issues and self/this references within the code throughout.
> Added code referencing `self=this`

- README.md
- Rexfile
Readme has comments and asides that will (obvs.) need sorting - also wording is a bit pants, all requires review before publishing or use.
> Updated Readme.md and added Rexfile

- src/frontend/components/button/lib/component.js
- src/frontend/components/button/lib/submit-field-button.js
- views/layout.tt
Made error for client-side and moved button functionality into new file
> Calc dropdown error fix

- src/frontend/components/data-table/lib/component.js
- Also appears to fix snapshot error
> Removed initial load error

- src/frontend/components/form-group/input/lib/component.js
- Also fixed an error in the URL used to search
> Fix for people filter

- lib/GADS.pm
DEV BRANCH CURRENTLY BORKEN
Fixed missing brackets in `unless` block
> IMPORTANT - Fix for missing brackets in "unless"

- lib/GADS.pm
Typo and variable declaration now fixed - Cypress and WebDriver should now run
> Fix for compile-time errors

- package.json
- src/frontend/components/button/lib/component.test.ts
- src/frontend/components/button/lib/create-report-button.test.ts
- src/frontend/components/button/lib/submit-field-button.test.ts
- src/frontend/components/form-group/input/lib/component.js
- src/frontend/components/help-view/lib/component.test.ts
- src/frontend/js/lib/util/filedrag/lib/filedrag.test.ts
- src/frontend/js/lib/util/mapper/formdataMapper.test.ts
- src/frontend/js/lib/util/mapper/formdataMapper.ts
- src/frontend/js/lib/util/typeahead/lib/TypeaheadBuilder.test.ts
- src/frontend/js/lib/util/upload/UploadControl.test.ts
- src/frontend/js/lib/util/upload/UploadControl.ts
- src/frontend/testing/globals.definitions.ts
- Cleaned up some testing code as a consequence of these changes
- Created new upload component
- Removed blueimp (to reduce bloat)
> Created upload component

- lib/GADS.pm
- views/snippets/header_table_form.tt
> Removed no_download_pdf from reporting

- src/frontend/components/button/_button.scss
- src/frontend/components/data-table/_data-table.scss
- src/frontend/components/data-table/lib/component.js
DataTables.net was using incorrect classes and definitions for rendering sorting etc. throughout the system, this has be rectified.
> Updated DataTables code

- lib/GADS.pm
Updated sort to allow sorting in view by multiple columns
> Modified sort

- lib/GADS.pm
- src/frontend/components/purge/_purge.scss
- src/frontend/css/stylesheets/general.scss
- views/purge.tt
- Added breadcrumbs to purge
- Modified report breadcrumbs to be clearer
> Added and updated breadcrumbs

- src/frontend/components/button/lib/submit-field-button.ts
- Updated global declarations in button code in order to mitigate possible errors
- Found code was looking for the `people-filter` element regardless of visibility - updated code to use value of dropdown in order to mitigate this
> Found bug in display conditions and fixed

- views/navigation/main_menu.tt
Added tags to menu imgs (to meet WCAG requirements).
> Added aria labels for logo imgs

- lib/GADS.pm
Have also removed options that were present for IE compatibility as this is no longer required as we no longer support the browser.
> Moved x-frame-options header out of user_logged_in check [B:459]

- cypress/e2e/functionality/08-data-view.cy.ts
- cypress/support/commands.ts
The data view was missing a number of options due to the exclusion of the count parameter in a previous fix for efficiency. A test has been added to ensure this doesn't happen unexpectedly again.
> Updated tests to check for relevant options [B:1798 addendum]

- bin/add-extension.pl
- lib/GADS.pm
- lib/GADS/Column.pm
- lib/GADS/Column/Autocur.pm
- lib/GADS/Column/Calc.pm
- lib/GADS/Column/Curval.pm
- lib/GADS/Column/Date.pm
- lib/GADS/Column/Daterange.pm
- lib/GADS/Column/File.pm
- lib/GADS/Column/Intgr.pm
- lib/GADS/Column/Person.pm
- lib/GADS/Filecheck.pm
- src/frontend/js/lib/util/errorHandler/lib/errorHandler.ts
- src/frontend/js/lib/util/upload/UploadControl.ts
- src/frontend/testing/globals.definitions.ts
Fixes include:
- User option fixes to annotate options that Users can't modify
- Checks to file types that check overrides on submission to prevent spoofing
- Changes to filecheck to check files on filesystem on submission rather than just uploads
- Minor fix to upload progress display
> Fixes for file uploads

- lib/GADS/Record.pm
- t/003_display_field.t
This reverts commit e532a06e81be4bfd859e71fcb1e2affa4d4a9431.
> Revert "Fix blanking of values user does not have access to" [B:1747]
